# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from asv_msgs/State.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import asv_msgs.msg

class State(genpy.Message):
  _md5sum = "772f6702c4f085d1def153b9e006f238"
  _type = "asv_msgs/State"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# The full state of a 3DOF surface vessel
# eta: (x,y,psi)
# nu:  (u,v,r)
ShipMetaData header
float64 x
float64 y
float64 psi
float64 u
float64 v
float64 r
================================================================================
MSG: asv_msgs/ShipMetaData
uint8 id
string name
float32 radius"""
  __slots__ = ['header','x','y','psi','u','v','r']
  _slot_types = ['asv_msgs/ShipMetaData','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,x,y,psi,u,v,r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(State, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = asv_msgs.msg.ShipMetaData()
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.psi is None:
        self.psi = 0.
      if self.u is None:
        self.u = 0.
      if self.v is None:
        self.v = 0.
      if self.r is None:
        self.r = 0.
    else:
      self.header = asv_msgs.msg.ShipMetaData()
      self.x = 0.
      self.y = 0.
      self.psi = 0.
      self.u = 0.
      self.v = 0.
      self.r = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.header.id))
      _x = self.header.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f6d.pack(_x.header.radius, _x.x, _x.y, _x.psi, _x.u, _x.v, _x.r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = asv_msgs.msg.ShipMetaData()
      end = 0
      start = end
      end += 1
      (self.header.id,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.name = str[start:end].decode('utf-8')
      else:
        self.header.name = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.header.radius, _x.x, _x.y, _x.psi, _x.u, _x.v, _x.r,) = _struct_f6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.header.id))
      _x = self.header.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f6d.pack(_x.header.radius, _x.x, _x.y, _x.psi, _x.u, _x.v, _x.r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = asv_msgs.msg.ShipMetaData()
      end = 0
      start = end
      end += 1
      (self.header.id,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.name = str[start:end].decode('utf-8')
      else:
        self.header.name = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.header.radius, _x.x, _x.y, _x.psi, _x.u, _x.v, _x.r,) = _struct_f6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_f6d = struct.Struct("<f6d")
