# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from asv_msgs/StateArray.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import asv_msgs.msg

class StateArray(genpy.Message):
  _md5sum = "05e43d15ff5eab094661932878032f08"
  _type = "asv_msgs/StateArray"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# An array of states
State[] states
================================================================================
MSG: asv_msgs/State
# The full state of a 3DOF surface vessel
# eta: (x,y,psi)
# nu:  (u,v,r)
ShipMetaData header
float64 x
float64 y
float64 psi
float64 u
float64 v
float64 r
================================================================================
MSG: asv_msgs/ShipMetaData
uint8 id
string name
float32 radius"""
  __slots__ = ['states']
  _slot_types = ['asv_msgs/State[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StateArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.states is None:
        self.states = []
    else:
      self.states = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.states:
        _v1 = val1.header
        buff.write(_struct_B.pack(_v1.id))
        _x = _v1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_f.pack(_v1.radius))
        _x = val1
        buff.write(_struct_6d.pack(_x.x, _x.y, _x.psi, _x.u, _x.v, _x.r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.states is None:
        self.states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.states = []
      for i in range(0, length):
        val1 = asv_msgs.msg.State()
        _v2 = val1.header
        start = end
        end += 1
        (_v2.id,) = _struct_B.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v2.name = str[start:end].decode('utf-8')
        else:
          _v2.name = str[start:end]
        start = end
        end += 4
        (_v2.radius,) = _struct_f.unpack(str[start:end])
        _x = val1
        start = end
        end += 48
        (_x.x, _x.y, _x.psi, _x.u, _x.v, _x.r,) = _struct_6d.unpack(str[start:end])
        self.states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.states:
        _v3 = val1.header
        buff.write(_struct_B.pack(_v3.id))
        _x = _v3.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_f.pack(_v3.radius))
        _x = val1
        buff.write(_struct_6d.pack(_x.x, _x.y, _x.psi, _x.u, _x.v, _x.r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.states is None:
        self.states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.states = []
      for i in range(0, length):
        val1 = asv_msgs.msg.State()
        _v4 = val1.header
        start = end
        end += 1
        (_v4.id,) = _struct_B.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v4.name = str[start:end].decode('utf-8')
        else:
          _v4.name = str[start:end]
        start = end
        end += 4
        (_v4.radius,) = _struct_f.unpack(str[start:end])
        _x = val1
        start = end
        end += 48
        (_x.x, _x.y, _x.psi, _x.u, _x.v, _x.r,) = _struct_6d.unpack(str[start:end])
        self.states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_6d = struct.Struct("<6d")
_struct_f = struct.Struct("<f")
