// Generated by gencpp from file asv_msgs/Offset.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_OFFSET_H
#define ASV_MSGS_MESSAGE_OFFSET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv_msgs
{
template <class ContainerAllocator>
struct Offset_
{
  typedef Offset_<ContainerAllocator> Type;

  Offset_()
    : P_ca(0.0)
    , Chi_ca(0.0)  {
    }
  Offset_(const ContainerAllocator& _alloc)
    : P_ca(0.0)
    , Chi_ca(0.0)  {
  (void)_alloc;
    }



   typedef double _P_ca_type;
  _P_ca_type P_ca;

   typedef double _Chi_ca_type;
  _Chi_ca_type Chi_ca;




  typedef boost::shared_ptr< ::asv_msgs::Offset_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::Offset_<ContainerAllocator> const> ConstPtr;

}; // struct Offset_

typedef ::asv_msgs::Offset_<std::allocator<void> > Offset;

typedef boost::shared_ptr< ::asv_msgs::Offset > OffsetPtr;
typedef boost::shared_ptr< ::asv_msgs::Offset const> OffsetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::Offset_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::Offset_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'asv_msgs': ['/media/psf/Home/svn/PhD/Autosea/sbmpc_catkin_ws/src/ros_asv_system/asv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::Offset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::Offset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::Offset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::Offset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::Offset_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::Offset_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::Offset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67c79bd0079a016b59fb0b6f517f39b2";
  }

  static const char* value(const ::asv_msgs::Offset_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67c79bd0079a016bULL;
  static const uint64_t static_value2 = 0x59fb0b6f517f39b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::Offset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/Offset";
  }

  static const char* value(const ::asv_msgs::Offset_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::Offset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 P_ca\n\
float64 Chi_ca\n\
";
  }

  static const char* value(const ::asv_msgs::Offset_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::Offset_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.P_ca);
      stream.next(m.Chi_ca);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Offset_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::Offset_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::Offset_<ContainerAllocator>& v)
  {
    s << indent << "P_ca: ";
    Printer<double>::stream(s, indent + "  ", v.P_ca);
    s << indent << "Chi_ca: ";
    Printer<double>::stream(s, indent + "  ", v.Chi_ca);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_OFFSET_H
