// Generated by gencpp from file asv_msgs/ShipMetaData.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_SHIPMETADATA_H
#define ASV_MSGS_MESSAGE_SHIPMETADATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv_msgs
{
template <class ContainerAllocator>
struct ShipMetaData_
{
  typedef ShipMetaData_<ContainerAllocator> Type;

  ShipMetaData_()
    : id(0)
    , name()
    , radius(0.0)  {
    }
  ShipMetaData_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _radius_type;
  _radius_type radius;




  typedef boost::shared_ptr< ::asv_msgs::ShipMetaData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::ShipMetaData_<ContainerAllocator> const> ConstPtr;

}; // struct ShipMetaData_

typedef ::asv_msgs::ShipMetaData_<std::allocator<void> > ShipMetaData;

typedef boost::shared_ptr< ::asv_msgs::ShipMetaData > ShipMetaDataPtr;
typedef boost::shared_ptr< ::asv_msgs::ShipMetaData const> ShipMetaDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::ShipMetaData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::ShipMetaData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'asv_msgs': ['/media/psf/Home/svn/PhD/Autosea/sbmpc_catkin_ws/src/ros_asv_system/asv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::ShipMetaData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::ShipMetaData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::ShipMetaData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a664eef656fd4f22be60ea17b5e54ee3";
  }

  static const char* value(const ::asv_msgs::ShipMetaData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa664eef656fd4f22ULL;
  static const uint64_t static_value2 = 0xbe60ea17b5e54ee3ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/ShipMetaData";
  }

  static const char* value(const ::asv_msgs::ShipMetaData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
string name\n\
float32 radius\n\
";
  }

  static const char* value(const ::asv_msgs::ShipMetaData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShipMetaData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::ShipMetaData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::ShipMetaData_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_SHIPMETADATA_H
