// Generated by gencpp from file asv_msgs/StateArray.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_STATEARRAY_H
#define ASV_MSGS_MESSAGE_STATEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <asv_msgs/State.h>

namespace asv_msgs
{
template <class ContainerAllocator>
struct StateArray_
{
  typedef StateArray_<ContainerAllocator> Type;

  StateArray_()
    : states()  {
    }
  StateArray_(const ContainerAllocator& _alloc)
    : states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::asv_msgs::State_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::asv_msgs::State_<ContainerAllocator> >::other >  _states_type;
  _states_type states;




  typedef boost::shared_ptr< ::asv_msgs::StateArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::StateArray_<ContainerAllocator> const> ConstPtr;

}; // struct StateArray_

typedef ::asv_msgs::StateArray_<std::allocator<void> > StateArray;

typedef boost::shared_ptr< ::asv_msgs::StateArray > StateArrayPtr;
typedef boost::shared_ptr< ::asv_msgs::StateArray const> StateArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::StateArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::StateArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'asv_msgs': ['/media/psf/Home/svn/PhD/Autosea/sbmpc_catkin_ws/src/ros_asv_system/asv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::StateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::StateArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::StateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::StateArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::StateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::StateArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::StateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05e43d15ff5eab094661932878032f08";
  }

  static const char* value(const ::asv_msgs::StateArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05e43d15ff5eab09ULL;
  static const uint64_t static_value2 = 0x4661932878032f08ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::StateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/StateArray";
  }

  static const char* value(const ::asv_msgs::StateArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::StateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# An array of states\n\
State[] states\n\
================================================================================\n\
MSG: asv_msgs/State\n\
# The full state of a 3DOF surface vessel\n\
# eta: (x,y,psi)\n\
# nu:  (u,v,r)\n\
ShipMetaData header\n\
float64 x\n\
float64 y\n\
float64 psi\n\
float64 u\n\
float64 v\n\
float64 r\n\
================================================================================\n\
MSG: asv_msgs/ShipMetaData\n\
uint8 id\n\
string name\n\
float32 radius\n\
";
  }

  static const char* value(const ::asv_msgs::StateArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::StateArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::StateArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::StateArray_<ContainerAllocator>& v)
  {
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::asv_msgs::State_<ContainerAllocator> >::stream(s, indent + "    ", v.states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_STATEARRAY_H
