// Generated by gencpp from file asv_msgs/WPArray.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_WPARRAY_H
#define ASV_MSGS_MESSAGE_WPARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <asv_msgs/WP.h>

namespace asv_msgs
{
template <class ContainerAllocator>
struct WPArray_
{
  typedef WPArray_<ContainerAllocator> Type;

  WPArray_()
    : wp_xy()  {
    }
  WPArray_(const ContainerAllocator& _alloc)
    : wp_xy(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::asv_msgs::WP_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::asv_msgs::WP_<ContainerAllocator> >::other >  _wp_xy_type;
  _wp_xy_type wp_xy;




  typedef boost::shared_ptr< ::asv_msgs::WPArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::WPArray_<ContainerAllocator> const> ConstPtr;

}; // struct WPArray_

typedef ::asv_msgs::WPArray_<std::allocator<void> > WPArray;

typedef boost::shared_ptr< ::asv_msgs::WPArray > WPArrayPtr;
typedef boost::shared_ptr< ::asv_msgs::WPArray const> WPArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::WPArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::WPArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'asv_msgs': ['/media/psf/Home/svn/PhD/Autosea/sbmpc_catkin_ws/src/ros_asv_system/asv_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::WPArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::WPArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::WPArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::WPArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::WPArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::WPArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::WPArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "311aa1759c0b5850ba11ceafcb7a7e61";
  }

  static const char* value(const ::asv_msgs::WPArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x311aa1759c0b5850ULL;
  static const uint64_t static_value2 = 0xba11ceafcb7a7e61ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::WPArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/WPArray";
  }

  static const char* value(const ::asv_msgs::WPArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::WPArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# WP array containing (x,y) \n\
WP[] wp_xy\n\
\n\
================================================================================\n\
MSG: asv_msgs/WP\n\
# Waypoint position\n\
# WP: (x,y)\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::asv_msgs::WPArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::WPArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wp_xy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WPArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::WPArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::WPArray_<ContainerAllocator>& v)
  {
    s << indent << "wp_xy[]" << std::endl;
    for (size_t i = 0; i < v.wp_xy.size(); ++i)
    {
      s << indent << "  wp_xy[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::asv_msgs::WP_<ContainerAllocator> >::stream(s, indent + "    ", v.wp_xy[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_WPARRAY_H
