hysteretic_controller:
  ros__parameters:
    state_topic_name: "/CSEI/observer/odom"
    ref_topic_name: "/CSE/references"
    publish_period_ms: 10
    controller:
      configuration_gains: [2., 2.]
      derivative_gains: [.5, .5, .5]
      parameter_gains: [5.0, 5.0, .1, .01, .01, 0.01, 0.01, 0.01, 0.01, 0.1, 0.01, 0.01, .001, .001, .001, 0.01, 0.01]
      xi_lb: [10., 15., 1., -3., 0., 0., 0., 0., 0., 0., 0., -2., -2., -2., -1., 0.5, 0.5]
      xi_ub: [20., 30., 5., 3., 10., 10., 10., 10., 10., 10., 10., 10., 2., 2., 2., 5., 5.]
      delta: 0.5236
      epsilon: 0.17
      global_heading_gain: 0.15
      local_heading_gain: 0.3
      xi_init: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.6]
