psbmpc_node:
	ros__parameters:
		enable_topic_stats: False
		topic_stats_topic_name: "psbmpc_stats"
		dynamic_obstacle_topic_name: "/psbmpc/do_estimates"
		state_topic_name: "/psbmpc/ownship_state"
		waypoints_topic_name: "/psbmpc/waypoints"
		reference_topic_name: "guidance/reference_trajectory"
		topic_stats_publish_period_ms: 1000
		deadline_duration_ms: 0
		trajectory_publish_period_ms: 5000
		# Kinematic ship model parameters
		ownship:
			l: 5.0
			w: 3.0
			T_U: 1.44
			T_chi: 0.92
			R_a: 5.0
			LOS_LD: 66.0
			LOS_K_i: 0.0
		grounding_hazard_manager:
			map_data_filename: "/grounding_hazard_data/trondheim/old version data/charts/land.shp"
			map_origin: [7042020, 269575]
		obstacle_manager:
			T_lost_limit: 15.0
			T_tracked_limit: 15.0
			obstacle_filter_on: false
		obstacle_predictor:
			r_ct: 10.0
			sigma_x: 0.01
			sigma_xy: 0.0
			sigma_y: 0.01
			gamma_x: 0.1
			gamma_y: 0.1
		cpe: 
			n_CE: 500
			n_MCSKF: 500
			alpha_n: 0.9
			gate: 11.618285980628054
			rho: 0.9
			max_it: 6
			r: 0.001
			q: 0.0008
		psbmpc:
			u_offsets: "[[1.0, 0.5, 0.0], [1.0, 0.5]]"
			# Course offsets in degrees, conversion to radians done in the parameter class
			chi_offsets: "[[-60.0, -45.0, -30.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 30.0, 45.0, 60.0], [-60.0, -45.0, -30.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 30.0, 45.0, 60.0]]"
			# CE: 0, MCSKF4D: 1
			cpe_method: 0
			# Linear: 0, ERK1: 1, ERK4: 2
			prediction_method: 1
			# LOS: 0, WPP: 1, CH: 2
			guidance_method: 0
			# Integer type parameters, see psbmpc_index.hpp file to see which parameter to change
			ipars: [2, 5, 1, 2, 2]
			
			# Double type parameters, see psbmpc_index.hpp file to see which parameter to change
			# phi_AH, phi_OT, phi_HO, phi_CR given in degrees, conversion to radians done in the parameter class
			dpars: [150.0, 0.5, 10.0, 5.0, 300.0, 300.0, 200.0, 3.0, 68.5, 68.5, 22.5, 68.5, 20.0, 20.0, 40.0, 6.0, 1.3, 1.6, 0.9, 1.2, 8.0, 40.0, 100.0, 5.0, 0.25, 0.01, 2.0]
			
